### ISSUE TITLE
trinity_butterfly_parallel issue

### ISSUE THREAD

**Issue by corina-simian** [transXpress/transXpress#48]
Hi,
I am trying to run the following command:
`nohup snakemake --latency-wait 60 --jobs 100 --config samples_file=sample.txt --cluster 'bsub -n 8 -R "rusage[mem=64000] span[hosts=1]" -oo log.bsub' &`

I am getting the following kind of errors in the `nohup.out`:
```
Error in rule trinity_butterfly_parallel:
    jobid: 458
    output: trinity_out_dir/parallel_jobs/completed_618
    log: logs/trinity_parallel618.log (check log file(s) for error message)
    shell:

    bash trinity_out_dir/parallel_jobs/job_618 &> logs/trinity_parallel618.log
    cp -p trinity_out_dir/parallel_jobs/job_618 trinity_out_dir/parallel_jobs/completed_618 &>> logs/trinity_parallel618.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: Job <4976080> is submitted to default queue <normal>.

Error executing rule trinity_butterfly_parallel on cluster (jobid: 458, external: Job <4976080> is submitted to default queue <normal>., jobscript: /mypath/transXpress/.snakemake/tmp.5n4q2rrc/snakejob.trinity_butterfly_parallel.458.sh).
For error details see the cluster log and the log files of the involved rule(s).
...
...
39 of 959 steps (4%) done
[Wed Nov  3 12:45:42 2021]
Finished job 761.
40 of 959 steps (4%) done
[Wed Nov  3 12:47:23 2021]
Finished job 824.
41 of 959 steps (4%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
Unfortunately the `logs/trinity_parallel618.log` is empty. This is not happening only for one job, but for many. All of the corresponding log files are empty.

I tried rerunning the pipeline several times without success.

I would appreciate any advice. Thanks.

**Comment by tomas-pluskal** [comment]
Hi Corina, does it happen reproducibly always for the same jobs, or does it happen at random? 

Note that you should have `-oo {log}.bsub`  in the snakemake command, see https://github.com/transXpress/transXpress/blob/master/transXpress.sh#L22
Then you will get another log file, like `logs/trinity_parallel618.log.bsub`

You can also try tp run the problematic command manually (e.g. `bash trinity_out_dir/parallel_jobs/job_618` and see what happens).

**Comment by corinasimian** [comment]
Hi Tomas, thank you for the advice. The jobs that fail seem to be random. I adjusted the command and now I do get output in the `logs/trinity_parallel*.log.bsub` files. I am getting the following kind of errors:
```
Building DAG of jobs...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/snakemake/__init__.py", line 709, in snakemake
    keepincomplete=keep_incomplete,
  File "/usr/local/lib/python3.6/dist-packages/snakemake/workflow.py", line 670, in execute
    dag.init()
  File "/usr/local/lib/python3.6/dist-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "/usr/local/lib/python3.6/dist-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "/usr/local/lib/python3.6/dist-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "/usr/local/lib/python3.6/dist-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: 'trinity_out_dir/read_partitions/Fb_0/CBin_68/c6896.trinity.reads.fa.out'
``` 
I had a look in the `trinity_out_dir/read_partitions/Fb_0/CBin_68` folder. Indeed, there is no `c6896.trinity.reads.fa.out` but there are  `c6896.trinity.reads.fa` and `c6896.trinity.reads.fa.out.Trinity.fasta`. Is it supposed to point to one of these and there is a configuration issue somewhere?

I also tried to run one the commands manually, but it did not help.
Thanks!

**Comment by CalounovaT** [comment]
Hi Corina,
could you please write what version of Trinity you are using?
To see the version, you can run following command: `conda list | grep trinity`

**Comment by corinasimian** [comment]
Hi,
The Trinity version is 2.9.1. Thank you.

**Comment by CalounovaT** [comment]
Ok, thanks for that.
I unfortunetely still do not understand the source of your problem with Trinity but you could try using newer version of Trinity.
In transXpress we expect users to use Trinity of version 2.11 or higher so maybe that could help.

**Comment by cyhkim** [comment]
Hi Tomas and Tereza,

I'm having a similar problem, and I'm using Trinity 2.12.0! Let me know if there is a solution for this problem. I can provide some details from the log if needed.

Thanks,
Colin

**Comment by CalounovaT** [comment]
@cyhkim 
Hi Colin,
could you please attach examples of log files of your failed jobs? I will look into it.

Tereza

**Comment by cyhkim** [comment]
Hi Tereza,

Yes of course! Here it is. Let me know if you need anything else, thank you!

Colin

[2021-11-15T131646.244039.snakemake.log](https://github.com/transXpress/transXpress/files/7564476/2021-11-15T131646.244039.snakemake.log)

**Comment by CalounovaT** [comment]
@cyhkim 
In your case Trinity part went fine but the pipeline produces errors when running tmhmm.py and Deeploc.
Could you please attach some examples of log files of failed tmhmm_parallel and deeploc_parallel jobs such as these two:
logs/tmhmm_102.log
logs/deeploc_114.log

Tereza

**Comment by cyhkim** [comment]
Hi Tereza,

I see. Here is the deeploc log file
[deeploc_114.log](https://github.com/transXpress/transXpress/files/7564633/deeploc_114.log)

As for the tmhmm log file, everything seems to be empty in the logs/tmhmm*.log files..! Let me know what you think might be happening here.

Colin

**Comment by tomas-pluskal** [comment]
The DeepLoc log says
```
Traceback (most recent call last):
  File "//lab/weng_scratch/deeploc/deeploc-1.0/bin/deeploc", line 13, in <module>
    from DeepLoc.models import *
ModuleNotFoundError: No module named 'DeepLoc'
```
So it seems deeploc is not installed correctly, at least in the conda environment that you are using. Have you tried running deeploc manually on some protein fasta file (in the same conda environment)?
