### ISSUE TITLE
trimmomatic partial write error with "java.io.IOException: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress#89]
Hi folks, 

Troubleshooting for a Moore lab member who is attempting to run a local transxpress run on our self-hosted computational server. The trimmomatic_parallel rule seems to have weird **writing** IO errors. See below error log. 2 of 4 trimmomatic runs completed successfully. 

The `mamba` installed environments, source files, working directories, are present on our [kernel driver](https://docs.ceph.com/en/reef/cephfs/mount-using-kernel-driver/) `cephfs` mounted centralized lab storage, that has 12 TB of storage available. The snakemake TMPDIR has also been set to the cephfs storage. In short, I've tried to exclude any sort of I/O with direct node mounted hardware (`/` or `/tmp`)

The fastq.gz files given to trimmomatic are available and readable start to finish (gz internal checksum passes)

The computational server has lots of CPU, RAM, etc resources available. 

I'm a bit stuck so throwing it out there in case anyone has seen it before. Should I blame:
1. Cephfs? Temporary glitch? -> Can't be fixed, just rerun
2. The `java` invocation of `trimmomatic` only having 1G of RAM? per `htop` -> `--Xms 512m -Xmx1g` (the trimmomatic_paralell rule says 10G, but that doesn't appear to get passed down?) -> ensure trimmomatic `java -jar` invocation actually gets the RAM that the rule states
3. Some sort of weird multithreading issue -> Run trimmomatic with 1 thread instead of 4, and a more recent java JVM?

```
cat trimmomatic_parallel04.log 
TrimmomaticPE: Started with arguments:
 -threads 4 /mnt/cephfs/Moore/moorelab/Sequencing_data/Lara/igm-storage2.ucsd.edu/240731_LH00444_0165_B22FMTKLT4/NA141_124_03_RNA_BU_S71_L002_R1_001.fastq.gz /mnt/cephfs/Moore/moorelab/Sequencing_data/Lara/igm-storage2.ucsd.edu/240731_LH00444_0165_B22FMTKLT4/NA141_124_03_RNA_BU_S71_L002_R2_001.fastq.gz trimmomatic/04.R1-P.qtrim.fastq.gz trimmomatic/04.R1-U.qtrim.fastq.gz trimmomatic/04.R2-P.qtrim.fastq.gz trimmomatic/04.R2-U.qtrim.fastq.gz ILLUMINACLIP:adapters.fasta:2:30:10 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25
Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATAAAGGAATGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT'
Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
Using Long Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG'
ILLUMINACLIP: Using 1 prefix pairs, 10 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Quality encoding detected as phred33
java.io.IOException: Resource temporarily unavailable
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
	at java.base/java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:148)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:291)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:362)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:338)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:152)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:217)
	at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
	at java.base/java.io.BufferedWriter.implWrite(BufferedWriter.java:334)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:313)
	at java.base/java.io.Writer.write(Writer.java:278)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Exception in thread "Thread-2" java.lang.RuntimeException: java.io.IOException: Resource temporarily unavailable
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:56)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.IOException: Resource temporarily unavailable
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
	at java.base/java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:148)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:291)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:362)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:338)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:152)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:217)
	at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
	at java.base/java.io.BufferedWriter.implWrite(BufferedWriter.java:334)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:313)
	at java.base/java.io.Writer.write(Writer.java:278)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	... 1 more
java.io.IOException: Resource temporarily unavailable
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
	at java.base/java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:148)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:291)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:362)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:338)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:152)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:217)
	at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
	at java.base/java.io.BufferedWriter.implWrite(BufferedWriter.java:334)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:313)
	at java.base/java.io.Writer.write(Writer.java:278)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Exception in thread "Thread-4" java.lang.RuntimeException: java.io.IOException: Resource temporarily unavailable
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:56)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.IOException: Resource temporarily unavailable
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
	at java.base/java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:148)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:291)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:362)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:338)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:152)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:217)
	at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
	at java.base/java.io.BufferedWriter.implWrite(BufferedWriter.java:334)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:313)
	at java.base/java.io.Writer.write(Writer.java:278)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	... 1 more
```

Output files for problematic `00` and `04` runs, are partially written with unexpected EOF:
```
-rw-rw-r--+  1 lduerr ad-unix         10 Aug 23 16:42 00.R2-U.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix         10 Aug 23 16:42 04.R2-U.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix   13740847 Aug 23 17:00 04.R1-U.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix   16678375 Aug 23 17:01 00.R1-U.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix 2105368446 Aug 23 17:01 04.R1-P.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix 2142603227 Aug 23 17:01 00.R1-P.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix 2101157066 Aug 23 17:01 04.R2-P.qtrim.fastq.gz
-rw-rw-r--+  1 lduerr ad-unix 2172005104 Aug 23 17:01 00.R2-P.qtrim.fastq.gz
```

**Comment by photocyte** [comment]
Oh, also another not so fun aspect is `trimmomatic` seems to hang forever but not exit after `java.io.IOException: Resource temporarily unavailable` , so `snakemake` is happy to keep it running indefinitely

**Comment by photocyte** [comment]
This is almost certainly due to an ongoing issue with our nodes ceph mounted filesystem
